/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedCandidatosRouteImport } from './routes/_authenticated/candidatos'
import { Route as AuthenticatedVagasVagaIdRouteImport } from './routes/_authenticated/vagas.$vagaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatosRoute = AuthenticatedCandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVagasVagaIdRoute =
  AuthenticatedVagasVagaIdRouteImport.update({
    id: '/vagas/$vagaId',
    path: '/vagas/$vagaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/candidatos': typeof AuthenticatedCandidatosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/vagas/$vagaId': typeof AuthenticatedVagasVagaIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/candidatos': typeof AuthenticatedCandidatosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/': typeof AuthenticatedIndexRoute
  '/vagas/$vagaId': typeof AuthenticatedVagasVagaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/candidatos': typeof AuthenticatedCandidatosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vagas/$vagaId': typeof AuthenticatedVagasVagaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/candidatos' | '/financeiro' | '/vagas/$vagaId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/candidatos' | '/financeiro' | '/' | '/vagas/$vagaId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/candidatos'
    | '/_authenticated/financeiro'
    | '/_authenticated/'
    | '/_authenticated/vagas/$vagaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidatos': {
      id: '/_authenticated/candidatos'
      path: '/candidatos'
      fullPath: '/candidatos'
      preLoaderRoute: typeof AuthenticatedCandidatosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vagas/$vagaId': {
      id: '/_authenticated/vagas/$vagaId'
      path: '/vagas/$vagaId'
      fullPath: '/vagas/$vagaId'
      preLoaderRoute: typeof AuthenticatedVagasVagaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCandidatosRoute: typeof AuthenticatedCandidatosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVagasVagaIdRoute: typeof AuthenticatedVagasVagaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCandidatosRoute: AuthenticatedCandidatosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVagasVagaIdRoute: AuthenticatedVagasVagaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
