/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CandidatosRouteImport } from './routes/candidatos'
import { Route as IndexRouteImport } from './routes/index'

const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatosRoute = CandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidatos': typeof CandidatosRoute
  '/financeiro': typeof FinanceiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidatos': typeof CandidatosRoute
  '/financeiro': typeof FinanceiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidatos': typeof CandidatosRoute
  '/financeiro': typeof FinanceiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidatos' | '/financeiro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidatos' | '/financeiro'
  id: '__root__' | '/' | '/candidatos' | '/financeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatosRoute: typeof CandidatosRoute
  FinanceiroRoute: typeof FinanceiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatos': {
      id: '/candidatos'
      path: '/candidatos'
      fullPath: '/candidatos'
      preLoaderRoute: typeof CandidatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatosRoute: CandidatosRoute,
  FinanceiroRoute: FinanceiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
